name: Financial Market Pipeline CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install dbt-snowflake

    - name: Validate dbt project
      run: |
        cd financial_market_dbt
        dbt debug --profiles-dir . --profile financial_market_dbt
      env:
        DBT_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_ACCOUNT }}
        DBT_SNOWFLAKE_USER: ${{ secrets.DBT_SNOWFLAKE_USER }}
        DBT_SNOWFLAKE_PASSWORD: ${{ secrets.DBT_SNOWFLAKE_PASSWORD }}